CREATE TABLE product (
	id SERIAL PRIMARY KEY,
	product_name text,
	price float
);

insert into product (product_name, price) values ('Pasta - Penne Primavera, Single', 17.29);
insert into product (product_name, price) values ('Pork - Butt, Boneless', 14.82);
insert into product (product_name, price) values ('Kellogs Special K Cereal', 16.54);
insert into product (product_name, price) values ('Wine - Pinot Noir Stoneleigh', 12.95);
insert into product (product_name, price) values ('Cheese - Swiss', 13.67);
insert into product (product_name, price) values ('Soup - Tomato Mush. Florentine', 7.75);
insert into product (product_name, price) values ('Apple - Fuji', 12.93);
insert into product (product_name, price) values ('Milk 2% 500 Ml', 10.5);
insert into product (product_name, price) values ('Cabbage - Savoy', 9.26);
insert into product (product_name, price) values ('Chocolate - Feathers', 23.97);
insert into product (product_name, price) values ('Lemon Balm - Fresh', 21.13);
insert into product (product_name, price) values ('Bread - Bagels, Plain', 14.96);
insert into product (product_name, price) values ('Duck - Fat', 9.55);
insert into product (product_name, price) values ('Coffee Beans - Chocolate', 6.02);
insert into product (product_name, price) values ('Ice Cream - Fudge Bars', 12.54);
insert into product (product_name, price) values ('Syrup - Kahlua Chocolate', 21.69);
insert into product (product_name, price) values ('Soup - Campbells Mac N Cheese', 12.73);
insert into product (product_name, price) values ('Salt And Pepper Mix - White', 10.57);
insert into product (product_name, price) values ('Chutney Sauce', 8.24);
insert into product (product_name, price) values ('Chilli Paste, Sambal Oelek', 13.52);
insert into product (product_name, price) values ('Sour Puss Sour Apple', 8.57);
insert into product (product_name, price) values ('Garlic - Elephant', 19.75);
insert into product (product_name, price) values ('Pur Value', 6.63);
insert into product (product_name, price) values ('Clam - Cherrystone', 10.05);
insert into product (product_name, price) values ('Lentils - Green Le Puy', 18.23);
insert into product (product_name, price) values ('Basil - Fresh', 23.4);
insert into product (product_name, price) values ('Spice - Chili Powder Mexican', 14.09);
insert into product (product_name, price) values ('Soap - Hand Soap', 23.46);
insert into product (product_name, price) values ('Wine - Bouchard La Vignee Pinot', 6.57);
insert into product (product_name, price) values ('Orange - Blood', 16.3);
insert into product (product_name, price) values ('Mints - Striped Red', 23.44);
insert into product (product_name, price) values ('Wine - Cotes Du Rhone', 13.02);
insert into product (product_name, price) values ('Cheese - Goat With Herbs', 14.82);
insert into product (product_name, price) values ('Cookies Almond Hazelnut', 11.44);
insert into product (product_name, price) values ('Fish - Halibut, Cold Smoked', 17.08);
insert into product (product_name, price) values ('Fond - Neutral', 21.24);
insert into product (product_name, price) values ('Garam Masala Powder', 11.0);
insert into product (product_name, price) values ('Beef Wellington', 20.25);
insert into product (product_name, price) values ('Scallops - In Shell', 5.43);
insert into product (product_name, price) values ('Pepperoni Slices', 24.09);
insert into product (product_name, price) values ('Longos - Lasagna Veg', 16.52);
insert into product (product_name, price) values ('Lemonade - Mandarin, 591 Ml', 14.62);
insert into product (product_name, price) values ('Garbage Bag - Clear', 14.05);
insert into product (product_name, price) values ('Salmon Atl.whole 8 - 10 Lb', 24.78);
insert into product (product_name, price) values ('Alize Red Passion', 22.56);
insert into product (product_name, price) values ('English Muffin', 21.94);
insert into product (product_name, price) values ('Cookies - Englishbay Chochip', 10.26);
insert into product (product_name, price) values ('Mushroom - Porcini Frozen', 13.76);
insert into product (product_name, price) values ('Container - Clear 16 Oz', 23.33);
insert into product (product_name, price) values ('Chocolate - Mi - Amere Semi', 18.83);
insert into product (product_name, price) values ('Butter Sweet', 17.95);
insert into product (product_name, price) values ('Danishes - Mini Cheese', 9.39);
insert into product (product_name, price) values ('Syrup - Monin, Irish Cream', 6.71);
insert into product (product_name, price) values ('Flour - Pastry', 13.99);
insert into product (product_name, price) values ('Greens Mustard', 6.54);
insert into product (product_name, price) values ('Peas - Pigeon, Dry', 23.75);
insert into product (product_name, price) values ('Snapple Raspberry Tea', 8.6);
insert into product (product_name, price) values ('Boogies', 11.04);
insert into product (product_name, price) values ('Lentils - Red, Dry', 9.3);
insert into product (product_name, price) values ('Icecream Bar - Del Monte', 9.24);
insert into product (product_name, price) values ('Mousse - Banana Chocolate', 22.17);
insert into product (product_name, price) values ('Bagel - Whole White Sesame', 13.14);
insert into product (product_name, price) values ('Flour - Strong', 24.56);
insert into product (product_name, price) values ('Veal - Inside Round / Top, Lean', 7.84);
insert into product (product_name, price) values ('Flour - Strong Pizza', 24.14);
insert into product (product_name, price) values ('Marsala - Sperone, Fine, D.o.c.', 10.03);
insert into product (product_name, price) values ('The Pop Shoppe - Lime Rickey', 7.41);
insert into product (product_name, price) values ('Crab - Blue, Frozen', 5.58);
insert into product (product_name, price) values ('Soup - Campbells, Chix Gumbo', 19.18);
insert into product (product_name, price) values ('Truffle Paste', 5.46);
insert into product (product_name, price) values ('Potato - Sweet', 16.35);
insert into product (product_name, price) values ('Cape Capensis - Fillet', 15.54);
insert into product (product_name, price) values ('Pasta - Rotini, Dry', 22.1);
insert into product (product_name, price) values ('Beef Flat Iron Steak', 19.33);
insert into product (product_name, price) values ('Cauliflower', 7.25);
insert into product (product_name, price) values ('Eel - Smoked', 9.22);
insert into product (product_name, price) values ('Lid - 10,12,16 Oz', 9.35);
insert into product (product_name, price) values ('Artichoke - Hearts, Canned', 21.5);
insert into product (product_name, price) values ('Tortillas - Flour, 10', 21.73);
insert into product (product_name, price) values ('Piping - Bags Quizna', 11.11);
insert into product (product_name, price) values ('Lettuce - Lambs Mash', 18.61);
insert into product (product_name, price) values ('Bread - Rye', 17.67);
insert into product (product_name, price) values ('Soup - Campbells Asian Noodle', 6.13);
insert into product (product_name, price) values ('Bacardi Breezer - Strawberry', 9.98);
insert into product (product_name, price) values ('Pastry - Choclate Baked', 24.32);
insert into product (product_name, price) values ('Sauce - Soya, Dark', 15.03);
insert into product (product_name, price) values ('Tomatoes - Hot House', 17.27);
insert into product (product_name, price) values ('Bread - Pain Au Liat X12', 6.78);
insert into product (product_name, price) values ('Chives - Fresh', 5.48);
insert into product (product_name, price) values ('Pasta - Penne, Rigate, Dry', 24.86);
insert into product (product_name, price) values ('Muffin - Mix - Creme Brule 15l', 14.03);
insert into product (product_name, price) values ('Bar Energy Chocchip', 14.3);
insert into product (product_name, price) values ('Beer - Mill St Organic', 9.97);
insert into product (product_name, price) values ('Rabbit - Frozen', 7.37);
insert into product (product_name, price) values ('Venison - Racks Frenched', 19.49);
insert into product (product_name, price) values ('Mustard - Individual Pkg', 15.95);
insert into product (product_name, price) values ('Fish - Base, Bouillion', 9.45);
insert into product (product_name, price) values ('Sauerkraut', 10.12);
insert into product (product_name, price) values ('Oil - Truffle, White', 19.47);
insert into product (product_name, price) values ('Sauerkraut', 21.73);